In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
#sentences 
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## define the vocabulary size
voc_size = 10000

In [6]:
#3One hot representation

one_hot_repre = [one_hot(words,voc_size) for words in sent]
one_hot_repre


[[7722, 5586, 4378, 857],
 [7722, 5586, 4378, 8740],
 [7722, 5094, 4378, 6650],
 [2463, 7856, 3401, 7963, 2176],
 [2463, 7856, 3401, 7963, 6661],
 [310, 7722, 3416, 4378, 2960],
 [6014, 6513, 3996, 7963]]

In [20]:
#word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences #sent length 
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np

In [22]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_repre,padding='pre',maxlen=sent_length)
embedded_doc

array([[   0,    0,    0,    0, 7722, 5586, 4378,  857],
       [   0,    0,    0,    0, 7722, 5586, 4378, 8740],
       [   0,    0,    0,    0, 7722, 5094, 4378, 6650],
       [   0,    0,    0, 2463, 7856, 3401, 7963, 2176],
       [   0,    0,    0, 2463, 7856, 3401, 7963, 6661],
       [   0,    0,    0,  310, 7722, 3416, 4378, 2960],
       [   0,    0,    0,    0, 6014, 6513, 3996, 7963]])

In [23]:
## feature representation
dim = 10


In [27]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length =sent_length))
model.compile('adam','mse')

s:\ML_DL_NLP_Bootcamp\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [28]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[[-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [ 0.0174736 , -0.04060174,  0.0358131 , -0.01347379,
         -0.02750766, -0.035269  , -0.01029651,  0.04903052,
          0.04778482,  0.03070981],
        [ 0.03159374, -0.00234926,  0.03626714,  0.00497732,
         -0.04928122,  0.03913388, -0.02867569,  0.0329966 ,
         -0.01069693,  0.03761968],
        [ 0.02096603, -0.01693094, -0.00181203,  0.0

In [30]:
embedded_doc[0]

array([   0,    0,    0,    0, 7722, 5586, 4378,  857])

In [33]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [-0.04917916,  0.03181639, -0.00450652, -0.03939243,
         -0.00258077, -0.04508423,  0.00089436, -0.01478525,
         -0.01194463,  0.02098075],
        [ 0.0174736 , -0.04060174,  0.0358131 , -0.01347379,
         -0.02750766, -0.035269  , -0.01029651,  0.04903052,
          0.04778482,  0.03070981],
        [ 0.03159374, -0.00234926,  0.03626714,  0.00497732,
         -0.04928122,  0.03913388, -0.02867569,  0.0329966 ,
         -0.01069693,  0.03761968],
        [ 0.02096603, -0.01693094, -0.00181203,  0.0